/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_sercd_SercdService */

#ifndef _Included_gnu_sercd_SercdService
#define _Included_gnu_sercd_SercdService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gnu_sercd_SercdService
 * Method:    main
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gnu_sercd_SercdService_main
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     gnu_sercd_SercdService
 * Method:    exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_sercd_SercdService_exit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class gnu_sercd_SercdService_ProxyState */

#ifndef _Included_gnu_sercd_SercdService_ProxyState
#define _Included_gnu_sercd_SercdService_ProxyState
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
